### ISSUE TITLE
Questions about Report process 

### ISSUE THREAD

**Issue by yaels818** [orellazri/ourstreets#2]
https://github.com/orellazri/ourstreets/wiki/Testing#09---reporting-a-hazard-as-member--hazard-type-cut-down-trees--not-adding-location-and-not-allowing-use-of-pictures

Another few points we should be clear about:
1. The user has to attach at least 1 photo? 
2. The user has to attach a location? Should we make sure the location is real and in this country?
3. What happens if a user does not mark the "Allow use of photos" checkbox? 
Maybe we should add (?) with extra info next to the checkbox to clarify for users. 

Thanks!

**Comment by orellazri** [comment]
1. Yes, and up to three photos
2. The user has to provide a location (either with the location detection, or by typing in an address manually, which will be implemented soon). I don't think we should make sure the location is real right now, but if there will be spare time, I can add a simple check to see if the longitude and latitude are in Israel.
3. When the report is uploaded to the database, there is a "consent" boolean field. If the user does not mark the checkbox, the consent is set to false, and the organization may not use the user's personal details later. An info tooltip seems like a great idea to me.

**Comment by yaels818** [comment]
Summary of what we discussed today:

2. Location type auto-complete - would check the location is real and within the country.

Thanks, I will update the relevant tests.
